---
openapi: 3.0.1
info:
  title: CourseSphere API
  version: v1
  description: API de gestão de cursos online
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
servers:
- url: http://localhost:3000
  description: Development
paths:
  "/api/v1/courses":
    get:
      summary: Lista cursos do usuário
      tags:
      - Courses
      security:
      - bearerAuth: []
      responses:
        '200':
          description: cursos listados
        '401':
          description: não autenticado
    post:
      summary: Cria um curso
      tags:
      - Courses
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: curso criado
        '422':
          description: dados inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                course:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Ruby on Rails
                    description:
                      type: string
                      example: Curso completo
                    start_date:
                      type: string
                      format: date
                      example: '2026-01-01'
                    end_date:
                      type: string
                      format: date
                      example: '2026-06-01'
                  required:
                  - name
                  - start_date
                  - end_date
  "/api/v1/courses/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Exibe um curso
      tags:
      - Courses
      security:
      - bearerAuth: []
      responses:
        '200':
          description: curso encontrado
        '404':
          description: não encontrado
    delete:
      summary: Exclui um curso
      tags:
      - Courses
      security:
      - bearerAuth: []
      responses:
        '204':
          description: curso excluído
        '403':
          description: não autorizado
